### ISSUE TITLE
caltech dataset

### ISSUE THREAD

**Issue by 111chengxuyuan** [Davidzhangyuanhan/NOAH#7]
When downloading Caltech datasets,why does it always report network errors? How can I solve this problem?

**Comment by Davidzhangyuanhan** [comment]
Have you downloaded other datasets in the VTAB-1k successfully?

**Comment by 111chengxuyuan** [comment]
Yes,all other datasets have been downloaded successfully

**Comment by Davidzhangyuanhan** [comment]
Try this:https://github.com/tensorflow/datasets/pull/2927

**Comment by 111chengxuyuan** [comment]
Ok,thank you

**Comment by 111chengxuyuan** [comment]
Hello, the problem of Caltech101 dataset has not been solved. It seems that because this dataset was updated again some time ago, the download link in tensorflow_datasets is out of date. I'm anxious to use this dataset. Can you send your processed Caltech101 dataset to my email? My email address is g_wenzhe@163.com , thank you very much!

**Comment by Davidzhangyuanhan** [comment]
HI,

we download Caltech101 in about 2021.11, and it is ok at that time.

we try to solve this problem asap, please stay tuned.

**Comment by 111chengxuyuan** [comment]
Ok,thank you.
